


#include "zealot_predefine.h"

enum ENUM_SVR_STATUS_1
{
    SVR_STATUS_1_1 = 1000,
    SVR_STATUS_1_2 = 1001,
    SVR_STATUS_1_3 = 1002,
};

enum ENUM_SVR_STATUS_2
{
    SVR_STATUS_2_1 = 2000,
    SVR_STATUS_2_2 = 2001,
    SVR_STATUS_2_3 = 2002,
};

ZCE_STATUS_ITEM_WITHNAME  SERVER_STATUS_1[] =
{
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_1_1, ZCE_STATUS_STATICS::PER_FIVE_MINTUES),
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_1_2, ZCE_STATUS_STATICS::PER_FIVE_MINTUES),
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_1_3, ZCE_STATUS_STATICS::PER_FIVE_MINTUES),
};

ZCE_STATUS_ITEM_WITHNAME  SERVER_STATUS_2[] =
{
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_2_1, ZCE_STATUS_STATICS::PER_FIVE_MINTUES),
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_2_2, ZCE_STATUS_STATICS::PER_FIVE_MINTUES),
    DEF_ZCE_STATUS_ITEM(SVR_STATUS_2_3, ZCE_STATUS_STATICS::ABSOLUTE_VALUE),
};

#define ZEALOT_FILE_NAME "ZEALOT.STATUS"

int test_server_status(int, char *[])
{
    ZCE_Server_Status::instance()->initialize(ZEALOT_FILE_NAME, 3, SERVER_STATUS_1, true);
    ZCE_Server_Status::instance()->add_status_item(3, SERVER_STATUS_1);
    ZCE_Server_Status::instance()->add_status_item(3, SERVER_STATUS_2);
    return 0;
}



