/******************************************************************************************
Copyright           : 2000-2004, Fullsail Technology Shenzhen, Company Limited.
FileName            : comm_error_code.h
Author              : Sail(ZENGXING,//Author name here
Version             :
Date Of Creation    : 2007年01月10日
Description         : framework所有的错误定义.

Others              :
Function List       :
1.  ......
Modification History:
1.Date  :
Author  :
Modification  :

README:
集中管理错误信息的原因是:
1.客户端可能也会同意使用错误定义
2.错误定义可能会复用

拜托在改错误定义的时候先把目光投射过来
1.定义错误返回值=COMMLIB利用5000-9999的数据，如果要上报，通过服务器+这个错误值上报，
2.上报错误定义给其他服务器的时候，可以通过TRANS_SEND_ERROR_CODE将错误定义和服务器类型和COMMLIB的错误一起传递出去。
3.其他服务器每个服务器使用自己的服务器的ID*10000+错误ID的序号
4.为什么数字不直接写 *SERVER_ERROR_CODE_INTERVAL +ID这样的方式，因为那样查询麻烦.我们实验过了。
5.在使用错误定义的时候，如果对客户端表现不同，尽量分开错误定义。如果一个要踢人，一个不要踢，尽量分开。
6.如果一个命令要踢人，则应该主动标示清楚。
7.如果是一个内部错误=不会影响到其他人=标明=
8.SOAR_RET_SUCC表示成功=内部统一使用

*/

#ifndef SOARING_LIB_ERROR_CODE_H_
#define SOARING_LIB_ERROR_CODE_H_

//---------------------------------------------------------------------------------------

//定义错误返回值=COMMLIB利用500-999的数据，如果要上报，通过服务器+这个错误值上报，
//其他服务器每个服务器使用自己的服务器的ID*1000+错误ID的序号

//为什么数字不直接写 *SERVER_ERROR_CODE_INTERVAL +ID这样的方式，因为那样查询麻烦
//我们实验过了。

class SOAR_RET
{
public:

    enum
    {
        FAIL_INTERNAL_ERORR = -1,

        ERROR_COMMLIB_BEGIN = 5000,
        ERROR_INTERNAL_ERORR = 5001,
        ERROR_PROCESS_MYSQLDB = 5002,
        ERROR_PROCESS_SQLITE = 5003,
        ERROR_INIT_RECEIVE_PIPE = 5011,
        ERROR_INIT_SEND_PIPE = 5012,
        ERROR_INIT_ERROR_PIPE = 5013,
        ERROR_PIPE_IS_FULL = 5014,
        ERROR_PIPE_IS_EMPTY = 5015,
        ERROR_GET_CFGFILE_CONFIG_FAIL = 5016,
        ERROR_GET_AUTO_CONN_CONFIG_FAIL = 5017,
        ERROR_NO_FOUND_DATA_FROM_DB = 5018,
        ERROR_MMAP_MALLOC_FAIL = 5019,
        ERROR_FIND_REPEAT_CMD_ID = 5020,
        ERROR_FIND_REPEAT_TRANSACTION_ID = 5021,
        ERROR_CANNOT_FIND_TRANSACTION_ID = 5022,
        ERROR_APPFRAME_BUFFER_SHORT = 5023,
        ERROR_DR_ENCODE_FAIL = 5024,
        ERROR_DR_DECODE_FAIL = 5025,
        ERROR_INVALID_DATA_ID = 5026,
        ERROR_SERVICES_INFO_CONFIG = 5027,
        ERROR_MML_ERROR = 5035,         //MML命令错误
        ERROR_MML_STRING_PARSE_FAIL = 5036,         //
        ERROR_CONSOLE_IS_CLOSED = 5037,
        ERROR_CONSOLE_START_FAIL = 5038,
        ERROR_EVENT_NOTIFY_FAIL = 5039,
        ERROR_EVENT_PROCESS_FAIL = 5040,
        ERROR_FRAME_DATA_IS_ERROR = 5041,
        ERROR_USERID_INCERTITUDE = 5042,
        ERROR_OCCUR_EXCEPTION = 5043,
        ERROR_FORK_FAIL = 5044,
        ERROR_STARTUP_TIP = 5045,
        ERROR_GET_STARTUP_CONFIG_FAIL = 5046,
        ERROR_WRITE_ERROR_PIDFILE = 5047,
        ERROR_INIT_TIMER_QUEUE = 5048,
        ERROR_FRAME_NOT_TAIL_IPINFO = 5049,
        ERROR_APPFRAME_ERROR = 5050,
        ERROR_APPFRAME_ENCRYPT_DECRYPT = 5051,
        ERROR_NOT_FIND_SERVICES_INFO = 5052,
        ERROR_INIT_DB_CONFIG = 5053,
        ERROR_GET_CONFIG_FROM_DB = 5054,
        ERROR_WRITE_PID_FILE_FAIL = 5055,
        ERROR_DIR_REPORT_INIT_ERROR = 5056,
        ERROR_NOT_FIND_FUNC = 5057,
        ERROR_NOT_ALLOW_CLIENT_VERSION = 5058,
        ERROR_INIT_SOARING_LIB_INFO_HASHTABLE = 5059,
        ERROR_INIT_SOARING_LIB_ITEM_LIST = 5060,
        ERROR_SHORT_PETINFO_CAPACITY = 5061,
        ERROR_SHORT_ITEMLIST_CAPACITY = 5062,
        ERROR_INSERT_PETINFO_FAIL = 5063,
        ERROR_INSERT_ITEMLIST_FAIL = 5064,
        ERROR_NOT_FIND_SOARING_LIB_INFO = 5065,
        ERROR_NOT_FIND_ITEM_LIST = 5066,
        ERROR_RECORD_LOG_FAIL_BUFFER_LACK = 5067,
        ERROR_NAVIGATION_TREE_XML_ERROR = 5068,
        ERROR_NAVIGATION_TREE_PARSE_FAIL = 5069,
        ERROR_NOT_FIND_NAVTREE_NODE = 5070,
        ERROR_APPFRAME_SESSION = 5071,
        ERROR_DIRTY_KEYWORD = 5072,
        ERROR_MMAP_CACHE_ERROR = 5073,
        ERROR_REPEAT_PROCESS_START = 5074,
        ERROR_PROCESS_MUTEX_ERROR = 5075,
        ERROR_NAVTREE_XML_FILE_FAIL = 5076,
        ERROR_INVALID_QQ_NUMBER = 5077,
        ERROR_INVALID_SOARING_LIB_TYPE = 5078,
        ERROR_INVALID_INTERNAL_IPADDRESS = 5079,
        ERROR_MMAP_CACHE_FULL = 5080,
        ERROR_MML_CONSOLE_FAIL = 5081,
        ERROR_LOAD_DLL_OR_SO_FAIL = 5082,
        ERROR_APPFRAME_SESSION_EXPIRE = 5083,
        ERROR_OGRE_FRAME_ERROR = 5084,
        ERROR_TRANS_NO_CLONE_COMMAND = 5085,
        ERROR_TRANS_HAS_FINISHED = 5086,
        ERROR_NOTIFY_SEND_QUEUE_DEQUEUE_FAIL = 5087,
        ERROR_NOTIFY_RECV_QUEUE_DEQUEUE_FAIL = 5088,
        ERROR_NOTIFY_SEND_QUEUE_ENQUEUE_FAIL = 5089,
        ERROR_NOTIFY_RECV_QUEUE_ENQUEUE_FAIL = 5090,
        ERROR_ZULU_INPUT_IPADDRESS_ERROR = 5091,
        ERROR_ZULU_CONNECT_SERVER_FAIL = 5092,
        ERROR_ZULU_SEND_PACKAGE_FAIL = 5093,
        ERROR_ZULU_RECEIVE_PACKAGE_FAIL = 5094,
        ERROR_ZULU_RECEIVE_OTHERS_COMMAND = 5095,
        ERROR_STRING_TO_SVCID_FAIL = 5096,
        ERROR_SERVICES_ID_INVALID = 5097,
        ERROR_STRING_TO_PEERINFO_FAIL = 5098,
        ERROR_MML_COMMAND_INVALID = 5099,                 //MML命令字无法识别
        ERROR_LOTTERY_RATIO_TOTAL = 5100,                 //博彩配置ratio总和错误
        ERROR_TRANSACTION_NEED_CMD_ERROR = 5111,                 //事务所期待的命令错误
        ERROR_SQLITE3_SQL_SYNTAX_ERROR = 5113,                 //sqlite3 SQL语法错误
        ERROR_SQLITE3_OPEN_DATABASE = 5114,                 //sqlite3 SQL语法错误
        ERROR_BOOL_EXPRESSION_ERROR = 5122,                 //BOOL表达式错误
        ERROR_BOOL_EXPRESSION_HAVE_ERR_CHAR = 5123,                 //BOOL表达式有错误字符
        ERROR_TASKID_PHASEID_NOT_MATCHING = 5124,                 //输入的阶段ID和任务ID无法匹配
        ERROR_SINGLE_SELECT_USER_INPUT_ERROR = 5125,                 //用户单选的的物品ID错误
        ERROR_TASK_ID_EQUAL_ZERO = 5126,                 //TASKID ==0，
        ERROR_CHECK_CONDITION_ERROR = 5127,                 //检查取得任务条件错误
        ERROR_GETTASK_CONDITION_RRROR = 5128,                 //取得任务条件粗欧文
        ERROR_ILLUSION_STRING_TO_ID_FAIL = 5129,                 //填写的字符串无法转换位ID
        ERROR_ILLUSION_CFG_COULD_HAVE_MODIFY = 5130,                 //梦想的配置发生改变，配置读取文件怀疑配置表发生了改变
        ERROR_ILLUSION_EXCEL_FILE_ERROR = 5133,                 //Excel文件错误
        ERROR_ZULU_LINK_DISCONNECT = 5154,                 //链接断开
        ERROR_FRAMEWORK_READ_ZERG_CFG_FAIL = 5155,
        ERROR_FRAMEWORK_READ_SELF_CFG_FAIL = 5156,
        ERROR_FRAMEWORK_READ_SVCID_CFG_FAIL = 5157,
        ERROR_FRAMEWORK_READ_APP_CFG_FAIL = 5158,
        ERROR_GET_CFGSVR_IP_BY_DNS = 5159,
        ERROR_GET_SVCID_FROM_CFGSVR = 5160,
        ERROR_GET_SVCIP_FROM_CFGSVR = 5161,
        ERROR_GET_CONFIG_FROM_CFGSVR = 5162,
        ERROR_GET_SLAVE_CFGSVR_INFO = 5163,
        ERROR_GET_CFGSVR_INVALID_START_ARGS = 5164,
        ERROR_INVALID_SERVICE_TYPE = 5165,
        ERROR_BAD_STAT_FILE_NAME = 5166,                  // 错误的stat文件名
        ERROR_STAT_MONITOR_NOT_INIT = 5167,                  // Soar_Stat_Monitor未初始化
        ERROR_SOCKET_CHANNEL_SEND_NO_INFO = 5168,                  // 使用socket channel发送数据没有对应业务的info
        ERROR_SOCKET_CHANNEL_SEND_BUS_FULL = 5169,                  // 使用socket channel发送数据发送管道满
        ERROR_SOCKET_CHANNEL_RECV_NO_INFO = 5170,                  // 使用socket channel接收数据没有对应业务的info
        ERROR_SOCKET_CHANNEL_RECV_BUS_EMPTY = 5171,                  // 使用socket channel接收数据管道为空
        ERROR_SOCKET_CHANNEL_INVALID_ARGS = 5172,                  // 使用socket channel组件参数错误
        ERROR_LOLO_SEND_RECV_CONN_NOT_SAME = 5173,                  // lolo收到的数据包服务器连接信息和发送的服务器不一致
        ERROR_COMMLIB_END = 9999,                  // framework错误码结束

        //ZERG
        ERR_ZERG_BEGIN = 20000,
        ERR_ZERG_FAIL_SOCKET_OP_ERROR = 20001,
        ERR_ZERG_GREATER_MAX_LEN_FRAME = 20002,
        ERR_ZERG_GREATER_DEFINE_LEN_FRAME = 20003,
        ERR_ZERG_SOCKET_CLOSE = 20004,
        ERR_ZERG_SERVER_ALREADY_LONGIN = 20006,
        ERR_ZERG_CONNECT_NO_FIND_SVCINFO = 20007,
        ERR_ZERG_INIT_RECEIVE_PIPE = 20008,
        ERR_ZERG_INIT_SEND_PIPE = 20009,
        ERR_ZERG_INIT_ERR_ZERG_PIPE = 20010,
        ERR_ZERG_NO_FIND_EVENT_HANDLE = 20011,
        ERR_ZERG_RECEIVE_PIPE_IS_FULL = 20012,
        ERR_ZERG_SEND_PIPE_IS_FULL = 20013,
        ERR_ZERG_ERROR_PIPE_IS_FULL = 20014,
        ERR_ZERG_GREAT_THAN_ERROR_TRY = 20015,
        ERR_ZERG_MMAP_MALLOC_FAIL = 20016,
        ERR_ZERG_INIT_ACCEPT_SOCKET_FAIL = 20017,
        ERR_ZERG_GET_STARTUP_CONFIG_FAIL = 20018,
        ERR_ZERG_GET_CFGFILE_CONFIG_FAIL = 20019,
        ERR_ZERG_GET_AUTO_CONN_CONFIG_FAIL = 20020,
        ERR_ZERG_OCCUR_EXCEPTION = 20021,
        ERR_ZERG_APPFRAME_ERROR = 20022,
        ERR_ZERG_COULD_NOT_ERR_ZERG_PROCESS = 20023,
        ERR_ZERG_SVCID_ALREADY_CONNECTED = 20024,
        ERR_ZERG_APPFRAME_CMD_ERROR = 20025,
        ERR_ZERG_INIT_TIMER_QUEUE = 20026,
        ERR_ZERG_INIT_LISTEN_PORT_FAIL = 20027,
        ERR_ZERG_SEND_FRAME_FAIL = 2028,
        ERR_ZERG_WRITE_PID_FILE_FAIL = 20029,
        ERR_ZERG_UNSAFE_PORT_WARN = 20030,
        ERR_ZERG_INIT_UPD_PORT_FAIL = 20031,
        ERR_ZERG_IP_RESTRICT_CHECK_FAIL = 20032,
        ERR_ZERG_UDPSESSION_NOFOUND = 20033,
        ERR_ZERG_UDPSESSION_FULL = 20034,
        ERR_ZERG_SVCTYPE_IS_NOT_ALLOW = 20035,
        ERR_ZERG_LOAD_OPERATION_KEY_FAIL = 20036,
        ERR_ZERG_ISNOT_CONNECT_SERVICES = 20037,
        ERR_ZERG_CHOOSE_AUTO_CONNECT_SERVICES = 20038,
        ERR_ZERG_CONFIG_GET_IP_FROM_CFGSVR = 20039,
        ERR_ZERG_INSERT_TYPETOIDTABLE_FAIL = 20040,
        ERR_ZERG_NO_FIND_SVCTYPE_RECORD = 20040,
        ERR_ZERG_CONFIG_REPEAT_SVCID = 20041,
        ERR_ZERG_END = 20999,

        ERR_OGRE_BEGIN = 21000,
        ERR_OGRE_SOCKET_OP_ERROR = 21001,
        ERR_OGRE_SOCKET_CLOSE = 21002,
        ERR_OGRE_RECEIVE_PIPE_IS_FULL = 21003,
        ERR_OGRE_ERROR_PIPE_IS_FULL = 21004,
        ERR_OGRE_NO_FIND_SERVICES_INFO = 21005,
        ERR_OGRE_INIT_LISTEN_PORT_FAIL = 21006,
        ERR_OGRE_GREAT_THAN_ERROR_TRY = 21007,
        ERR_OGRE_SEND_FRAME_FAIL = 21008,
        ERR_OGRE_NO_FIND_EVENT_HANDLE = 21009,
        ERR_OGRE_SERVER_ALREADY_LONGIN = 21010,
        ERR_OGRE_SEND_FRAME_TOO_LEN = 21011,
        ERR_OGRE_INIT_COMM_MANAGER = 21012,
        ERR_OGRE_INIT_UDP_PEER = 21013,
        ERR_OGRE_UNSAFE_PORT_WARN = 21014,
        ERR_OGRE_IP_RESTRICT_CHECK_FAIL = 21015,
        ERR_OGRE_GREATER_MAX_LEN_FRAME = 21016,
        ERR_OGRE_CFG_REPEAT_PEERID = 21017,
        ERR_OGRE_CANNOT_FIND_PEERID = 21018,
        ERR_OGRE_ALREADY_CONNECTED = 21019,
        ERR_OGRE_END = 21999,

        // cfgsvr错误码，使用新type
        ERR_CFG_BEGIN = 50000,
        ERR_CFG_CONFIG_MD5_NOT_FOUND = 50001,
        ERR_CFG_CONFIG_INFO_NOT_FOUND = 50002,
        ERR_CFG_CONFIG_LEN_ERROR = 50003,
        ERR_CFG_SERVICE_NOT_FOUND = 50004,
        ERR_CFG_SERVICE_UPDATE_TYPE_ERROR = 50005,
        ERR_CFG_SERVICE_IP_REPEAT = 50006,
        ERR_CFG_SERVICE_ID_REPEAT = 50007,
        ERR_CFG_BUFFER_NOT_ENOUGH = 50008,
        ERR_CFG_FILE_OPERATE_ERROR = 50009,
        ERR_CFG_DB_INIT_ERROR = 50010,
        ERR_CFG_DB_QUERY_ERROR = 50011,
        ERR_CFG_DB_RESULT_ERROR = 50012,
        ERR_CFG_DB_EXIT_ERROR = 50013,
        ERR_CFG_XML_MERGE_ERROR = 50014,
        ERR_CFG_ARGS_INVALID = 50015,
        ERR_CFG_UNPACK_ERROR = 50016,
        ERR_CFG_PKG_CMD_ERROR = 50017,
        ERR_CFG_NOT_FOUND_SVCIP_INFO = 50018,
        ERR_CFG_NOT_FOUND_SVCID_INFO = 50019,
        ERR_CFG_NOT_FOUND_SLAVE_INFO = 50020,
        ERR_CFG_NOT_FOUND_DEPLOY_INFO = 50021,
        ERR_CFG_GET_CONFIG_ERROR = 50022,
        ERR_CFG_NOT_FOUND_SVR_CONFIG_LIST = 50023,
        ERR_CFG_SYN_CONFIG_ERROR = 50024,
        ERR_CFG_SYN_UPDATE_CONFIG_ERROR = 50025,
        ERR_CFG_MASTER_UPDATE_CONFIG_ERROR = 50026,
        ERR_CFG_DEPLOY_INFO_NUM_TOO_LARGE = 50027,
        ERR_CFG_END = 50999,

        //PROXY
        ERR_PROXY_BEGIN = 51000,
        ERR_PROXY_APPFRAME_CMD_ERROR = 51001,
        ERR_PROXY_SEND_PIPE_IS_FULL = 51002,
        ERR_PROXY_RECEIVE_ERROR_FRAME = 51003,
        ERR_PROXY_RCVSVC_TYPE_ERROR = 51004,
        ERR_PROXY_END = 51999,
    };

    ///
    static const char *error_string(int error_id);
};

//---------------------------------------------------------------------------------------------

#endif //#ifndef SOARING_LIB_ERROR_CODE_H_
