/******************************************************************************************
Copyright           : 2000-2004, Fullsail Technology (Shenzhen) Company Limited.
FileName            : comm_error_code.h
Author              : Sail(ZENGXING)//Author name here
Version             :
Date Of Creation    : 2007年01月10日
Description         : framework所有的错误定义.

Others              :
Function List       :
1.  ......
Modification History:
1.Date  :
Author  :
Modification  :

README:
集中管理错误信息的原因是:
1.客户端可能也会同意使用错误定义
2.错误定义可能会复用

拜托在改错误定义的时候先把目光投射过来
1.定义错误返回值,COMMLIB利用5000-9999的数据，如果要上报，通过服务器+这个错误值上报，
2.上报错误定义给其他服务器的时候，可以通过TRANS_SEND_ERROR_CODE将错误定义和服务器类型和COMMLIB的错误一起传递出去。
3.其他服务器每个服务器使用自己的服务器的ID*10000+错误ID的序号
4.为什么数字不直接写 *SERVER_ERROR_CODE_INTERVAL +ID这样的方式，因为那样查询麻烦.我们实验过了。
5.在使用错误定义的时候，如果对客户端表现不同，尽量分开错误定义。如果一个要踢人，一个不要踢，尽量分开。
6.如果一个命令要踢人，则应该主动标示清楚。
7.如果是一个内部错误,不会影响到其他人,标明,
8.SOAR_RET_SUCC表示成功,内部统一使用

******************************************************************************************/

#ifndef SOARING_LIB_ERROR_CODE_H_
#define SOARING_LIB_ERROR_CODE_H_

//---------------------------------------------------------------------------------------

//定义错误返回值,COMMLIB利用500-999的数据，如果要上报，通过服务器+这个错误值上报，
//其他服务器每个服务器使用自己的服务器的ID*10000+错误ID的序号

//为什么数字不直接写 *SERVER_ERROR_CODE_INTERVAL +ID这样的方式，因为那样查询麻烦
//我们实验过了。

BEGINDEFSYMBOL(SOAR_RET, COMM_RETURN_ID)
DEFSYMBOLTOID(FAIL_INTERNAL_ERORR                   , -1)
DEFSYMBOLTOID(SOAR_RET_SUCC                          , 0)

// framework错误码开始
DEFSYMBOLTOID(ERROR_COMMLIB_BEGIN                   , 5000)
DEFSYMBOLTOID(ERROR_INTERNAL_ERORR                  , 5001)
DEFSYMBOLTOID(ERROR_PROCESS_C4ACACHE                , 5002)
DEFSYMBOLTOID(ERROR_PROCESS_MYSQLDB                 , 5003)
DEFSYMBOLTOID(ERROR_PROCESS_SQLITE                  , 5004)
DEFSYMBOLTOID(ERROR_INIT_RECEIVE_PIPE               , 5011)
DEFSYMBOLTOID(ERROR_INIT_SEND_PIPE                  , 5012)
DEFSYMBOLTOID(ERROR_INIT_ERROR_PIPE                 , 5013)
DEFSYMBOLTOID(ERROR_PIPE_IS_FULL                    , 5014)
DEFSYMBOLTOID(ERROR_PIPE_IS_EMPTY                   , 5015)
DEFSYMBOLTOID(ERROR_GET_CFGFILE_CONFIG_FAIL         , 5016)
DEFSYMBOLTOID(ERROR_GET_AUTO_CONN_CONFIG_FAIL       , 5017)
DEFSYMBOLTOID(ERROR_NO_FOUND_DATA_FROM_DB           , 5018)
DEFSYMBOLTOID(ERROR_MMAP_MALLOC_FAIL                , 5019)
DEFSYMBOLTOID(ERROR_FIND_REPEAT_CMD_ID              , 5020)
DEFSYMBOLTOID(ERROR_FIND_REPEAT_TRANSACTION_ID      , 5021)
DEFSYMBOLTOID(ERROR_CANNOT_FIND_TRANSACTION_ID      , 5022)
DEFSYMBOLTOID(ERROR_APPFRAME_BUFFER_SHORT           , 5023)
DEFSYMBOLTOID(ERROR_CDR_ENCODE_FAIL                 , 5024)
DEFSYMBOLTOID(ERROR_CDR_DECODE_FAIL                 , 5025)
DEFSYMBOLTOID(ERROR_INVALID_DATA_ID                 , 5026)
DEFSYMBOLTOID(ERROR_SERVICES_INFO_CONFIG            , 5027)
DEFSYMBOLTOID(ERROR_MML_ERROR                       , 5035)          //MML命令错误
DEFSYMBOLTOID(ERROR_MML_STRING_PARSE_FAIL           , 5036)          //
DEFSYMBOLTOID(ERROR_CONSOLE_IS_CLOSED               , 5037)
DEFSYMBOLTOID(ERROR_CONSOLE_START_FAIL              , 5038)
DEFSYMBOLTOID(ERROR_EVENT_NOTIFY_FAIL               , 5039)
DEFSYMBOLTOID(ERROR_EVENT_PROCESS_FAIL              , 5040)
DEFSYMBOLTOID(ERROR_FRAME_DATA_IS_ERROR             , 5041)
DEFSYMBOLTOID(ERROR_QQUIN_INCERTITUDE               , 5042)
DEFSYMBOLTOID(ERROR_OCCUR_EXCEPTION                 , 5043)
DEFSYMBOLTOID(ERROR_FORK_FAIL                       , 5044)
DEFSYMBOLTOID(ERROR_STARTUP_TIP                     , 5045)
DEFSYMBOLTOID(ERROR_GET_STARTUP_CONFIG_FAIL         , 5046)
DEFSYMBOLTOID(ERROR_WRITE_ERROR_PIDFILE             , 5047)
DEFSYMBOLTOID(ERROR_INIT_TIMER_QUEUE                , 5048)
DEFSYMBOLTOID(ERROR_FRAME_NOT_TAIL_IPINFO           , 5049)
DEFSYMBOLTOID(ERROR_APPFRAME_ERROR                  , 5050)
DEFSYMBOLTOID(ERROR_APPFRAME_ENCRYPT_DECRYPT        , 5051)
DEFSYMBOLTOID(ERROR_NOT_FIND_SERVICES_INFO          , 5052)
DEFSYMBOLTOID(ERROR_INIT_DB_CONFIG                  , 5053)
DEFSYMBOLTOID(ERROR_GET_CONFIG_FROM_DB              , 5054)
DEFSYMBOLTOID(ERROR_WRITE_PID_FILE_FAIL             , 5055)
DEFSYMBOLTOID(ERROR_DIR_REPORT_INIT_ERROR           , 5056)
DEFSYMBOLTOID(ERROR_NOT_FIND_FUNC                   , 5057)
DEFSYMBOLTOID(ERROR_NOT_ALLOW_CLIENT_VERSION        , 5058)
DEFSYMBOLTOID(ERROR_INIT_SOARING_LIB_INFO_HASHTABLE  , 5059)
DEFSYMBOLTOID(ERROR_INIT_SOARING_LIB_ITEM_LIST       , 5060)
DEFSYMBOLTOID(ERROR_SHORT_PETINFO_CAPACITY          , 5061)
DEFSYMBOLTOID(ERROR_SHORT_ITEMLIST_CAPACITY         , 5062)
DEFSYMBOLTOID(ERROR_INSERT_PETINFO_FAIL             , 5063)
DEFSYMBOLTOID(ERROR_INSERT_ITEMLIST_FAIL            , 5064)
DEFSYMBOLTOID(ERROR_NOT_FIND_SOARING_LIB_INFO        , 5065)
DEFSYMBOLTOID(ERROR_NOT_FIND_ITEM_LIST              , 5066)
DEFSYMBOLTOID(ERROR_RECORD_LOG_FAIL_BUFFER_LACK     , 5067)
DEFSYMBOLTOID(ERROR_NAVIGATION_TREE_XML_ERROR       , 5068)
DEFSYMBOLTOID(ERROR_NAVIGATION_TREE_PARSE_FAIL      , 5069)
DEFSYMBOLTOID(ERROR_NOT_FIND_NAVTREE_NODE           , 5070)
DEFSYMBOLTOID(ERROR_APPFRAME_SESSION                , 5071)
DEFSYMBOLTOID(ERROR_DIRTY_KEYWORD                   , 5072)
DEFSYMBOLTOID(ERROR_MMAP_CACHE_ERROR                , 5073)
DEFSYMBOLTOID(ERROR_REPEAT_PROCESS_START            , 5074)
DEFSYMBOLTOID(ERROR_PROCESS_MUTEX_ERROR             , 5075)
DEFSYMBOLTOID(ERROR_NAVTREE_XML_FILE_FAIL           , 5076)
DEFSYMBOLTOID(ERROR_INVALID_QQ_NUMBER               , 5077)
DEFSYMBOLTOID(ERROR_INVALID_SOARING_LIB_TYPE           , 5078)
DEFSYMBOLTOID(ERROR_INVALID_INTERNAL_IPADDRESS      , 5079)
DEFSYMBOLTOID(ERROR_MMAP_CACHE_FULL                 , 5080)
DEFSYMBOLTOID(ERROR_MML_CONSOLE_FAIL                , 5081)
DEFSYMBOLTOID(ERROR_LOAD_DLL_OR_SO_FAIL             , 5082)
DEFSYMBOLTOID(ERROR_APPFRAME_SESSION_EXPIRE         , 5083)
DEFSYMBOLTOID(ERROR_OGRE_FRAME_ERROR                , 5084)
DEFSYMBOLTOID(ERROR_TRANS_NO_CLONE_COMMAND          , 5085)
DEFSYMBOLTOID(ERROR_TRANS_HAS_FINISHED              , 5086)
DEFSYMBOLTOID(ERROR_NOTIFY_SEND_QUEUE_DEQUEUE_FAIL  , 5087)
DEFSYMBOLTOID(ERROR_NOTIFY_RECV_QUEUE_DEQUEUE_FAIL  , 5088)
DEFSYMBOLTOID(ERROR_NOTIFY_SEND_QUEUE_ENQUEUE_FAIL  , 5089)
DEFSYMBOLTOID(ERROR_NOTIFY_RECV_QUEUE_ENQUEUE_FAIL  , 5090)
DEFSYMBOLTOID(ERROR_ZULU_INPUT_IPADDRESS_ERROR      , 5091)
DEFSYMBOLTOID(ERROR_ZULU_CONNECT_SERVER_FAIL        , 5092)
DEFSYMBOLTOID(ERROR_ZULU_SEND_PACKAGE_FAIL          , 5093)
DEFSYMBOLTOID(ERROR_ZULU_RECEIVE_PACKAGE_FAIL       , 5094)
DEFSYMBOLTOID(ERROR_ZULU_RECEIVE_OTHERS_COMMAND     , 5095)
DEFSYMBOLTOID(ERROR_MML_COMMAND_INVALID             , 5096)                 //MML命令字无法识别
DEFSYMBOLTOID(ERROR_LOTTERY_RATIO_TOTAL             , 5097)                 //博彩配置ratio总和错误
DEFSYMBOLTOID(ERROR_TRANSACTION_NEED_CMD_ERROR      , 5098)                 //事务所期待的命令错误
DEFSYMBOLTOID(ERROR_SQLITE3_SQL_SYNTAX_ERROR        , 5113)                 //sqlite3 SQL语法错误
DEFSYMBOLTOID(ERROR_SQLITE3_OPEN_DATABASE           , 5114)                 //sqlite3 SQL语法错误
DEFSYMBOLTOID(ERROR_BOOL_EXPRESSION_ERROR           , 5122)                 //BOOL表达式错误
DEFSYMBOLTOID(ERROR_BOOL_EXPRESSION_HAVE_ERR_CHAR   , 5123)                 //BOOL表达式有错误字符
DEFSYMBOLTOID(ERROR_TASKID_PHASEID_NOT_MATCHING     , 5124)                 //输入的阶段ID和任务ID无法匹配
DEFSYMBOLTOID(ERROR_SINGLE_SELECT_USER_INPUT_ERROR  , 5125)                 //用户单选的的物品ID错误
DEFSYMBOLTOID(ERROR_TASK_ID_EQUAL_ZERO              , 5126)                 //TASKID ==0，
DEFSYMBOLTOID(ERROR_CHECK_CONDITION_ERROR           , 5127)                 //检查取得任务条件错误
DEFSYMBOLTOID(ERROR_GETTASK_CONDITION_RRROR         , 5128)                 //取得任务条件粗欧文
DEFSYMBOLTOID(ERROR_ILLUSION_STRING_TO_ID_FAIL      , 5129)                 //填写的字符串无法转换位ID
DEFSYMBOLTOID(ERROR_ILLUSION_CFG_COULD_HAVE_MODIFY  , 5130)                 //梦想的配置发生改变，配置读取文件怀疑配置表发生了改变
DEFSYMBOLTOID(ERROR_ILLUSION_EXCEL_FILE_ERROR       , 5133)                 //Excel文件错误
DEFSYMBOLTOID(ERROR_ZULU_LINK_DISCONNECT            , 5154)                 //链接断开
DEFSYMBOLTOID(ERROR_FRAMEWORK_READ_ZERG_CFG_FAIL    , 5155)
DEFSYMBOLTOID(ERROR_FRAMEWORK_READ_SELF_CFG_FAIL    , 5156)
DEFSYMBOLTOID(ERROR_FRAMEWORK_READ_SVCID_CFG_FAIL   , 5157)
DEFSYMBOLTOID(ERROR_FRAMEWORK_READ_APP_CFG_FAIL     , 5158)
DEFSYMBOLTOID(ERROR_GET_CFGSVR_IP_BY_DNS            , 5159)
DEFSYMBOLTOID(ERROR_GET_SVCID_FROM_CFGSVR           , 5160)
DEFSYMBOLTOID(ERROR_GET_SVCIP_FROM_CFGSVR           , 5161)
DEFSYMBOLTOID(ERROR_GET_CONFIG_FROM_CFGSVR          , 5162)
DEFSYMBOLTOID(ERROR_GET_SLAVE_CFGSVR_INFO           , 5163)
DEFSYMBOLTOID(ERROR_GET_CFGSVR_INVALID_START_ARGS   , 5164)
DEFSYMBOLTOID(ERROR_INVALID_SERVICE_TYPE            , 5165)
DEFSYMBOLTOID(ERROR_BAD_STAT_FILE_NAME              , 5166)                  // 错误的stat文件名
DEFSYMBOLTOID(ERROR_STAT_MONITOR_NOT_INIT           , 5167)                  // Comm_Stat_Monitor未初始化
DEFSYMBOLTOID(ERROR_SOCKET_CHANNEL_SEND_NO_INFO     , 5168)                  // 使用socket channel发送数据没有对应业务的info
DEFSYMBOLTOID(ERROR_SOCKET_CHANNEL_SEND_BUS_FULL    , 5169)                  // 使用socket channel发送数据发送管道满
DEFSYMBOLTOID(ERROR_SOCKET_CHANNEL_RECV_NO_INFO     , 5170)                  // 使用socket channel接收数据没有对应业务的info
DEFSYMBOLTOID(ERROR_SOCKET_CHANNEL_RECV_BUS_EMPTY   , 5171)                  // 使用socket channel接收数据管道为空
DEFSYMBOLTOID(ERROR_SOCKET_CHANNEL_INVALID_ARGS     , 5172)                  // 使用socket channel组件参数错误
DEFSYMBOLTOID(ERROR_LOLO_SEND_RECV_CONN_NOT_SAME    , 5173)                  // lolo收到的数据包服务器连接信息和发送的服务器不一致
DEFSYMBOLTOID(ERROR_COMMLIB_END                     , 9999)                  // framework错误码结束

// cfgsvr错误码，使用新type
DEFSYMBOLTOID(ERR_CFG_BEGIN                         , 10000)
DEFSYMBOLTOID(ERR_CFG_CONFIG_MD5_NOT_FOUND          , 10001)
DEFSYMBOLTOID(ERR_CFG_CONFIG_INFO_NOT_FOUND         , 10002)
DEFSYMBOLTOID(ERR_CFG_CONFIG_LEN_ERROR              , 10003)
DEFSYMBOLTOID(ERR_CFG_SERVICE_NOT_FOUND             , 10004)
DEFSYMBOLTOID(ERR_CFG_SERVICE_UPDATE_TYPE_ERROR     , 10005)
DEFSYMBOLTOID(ERR_CFG_SERVICE_IP_REPEAT             , 10006)
DEFSYMBOLTOID(ERR_CFG_SERVICE_ID_REPEAT             , 10007)
DEFSYMBOLTOID(ERR_CFG_BUFFER_NOT_ENOUGH             , 10008)
DEFSYMBOLTOID(ERR_CFG_FILE_OPERATE_ERROR            , 10009)
DEFSYMBOLTOID(ERR_CFG_DB_INIT_ERROR                 , 10010)
DEFSYMBOLTOID(ERR_CFG_DB_QUERY_ERROR                , 10011)
DEFSYMBOLTOID(ERR_CFG_DB_RESULT_ERROR               , 10012)
DEFSYMBOLTOID(ERR_CFG_DB_EXIT_ERROR                 , 10013)
DEFSYMBOLTOID(ERR_CFG_XML_MERGE_ERROR               , 10014)
DEFSYMBOLTOID(ERR_CFG_ARGS_INVALID                  , 10015)
DEFSYMBOLTOID(ERR_CFG_UNPACK_ERROR                  , 10016)
DEFSYMBOLTOID(ERR_CFG_PKG_CMD_ERROR                 , 10017)
DEFSYMBOLTOID(ERR_CFG_NOT_FOUND_SVCIP_INFO          , 10018)
DEFSYMBOLTOID(ERR_CFG_NOT_FOUND_SVCID_INFO          , 10019)
DEFSYMBOLTOID(ERR_CFG_NOT_FOUND_SLAVE_INFO          , 10020)
DEFSYMBOLTOID(ERR_CFG_NOT_FOUND_DEPLOY_INFO         , 10021)
DEFSYMBOLTOID(ERR_CFG_GET_CONFIG_ERROR              , 10022)
DEFSYMBOLTOID(ERR_CFG_NOT_FOUND_SVR_CONFIG_LIST     , 10023)
DEFSYMBOLTOID(ERR_CFG_SYN_CONFIG_ERROR              , 10024)
DEFSYMBOLTOID(ERR_CFG_SYN_UPDATE_CONFIG_ERROR       , 10025)
DEFSYMBOLTOID(ERR_CFG_MASTER_UPDATE_CONFIG_ERROR    , 10026)
DEFSYMBOLTOID(ERR_CFG_DEPLOY_INFO_NUM_TOO_LARGE     , 10027)
DEFSYMBOLTOID(ERR_CFG_END                           , 19999)

//proxysvr错误吗，使用新type
DEFSYMBOLTOID(ERR_PROXY_BEGIN                       , 40000)
DEFSYMBOLTOID(ERR_PROXY_APPFRAME_CMD_ERROR          , 40001)
DEFSYMBOLTOID(ERR_PROXY_SEND_PIPE_IS_FULL           , 40002)
DEFSYMBOLTOID(ERR_PROXY_RECEIVE_ERROR_FRAME         , 40003)
DEFSYMBOLTOID(ERR_PROXY_RCVSVC_TYPE_ERROR           , 40004)
DEFSYMBOLTOID(ERR_PROXY_END                         , 49999)

// zerg的错误码，为何这个服务的错误码值要这么高？
DEFSYMBOLTOID(ERR_ZERG_BEGIN                        , 290010000)
DEFSYMBOLTOID(ERR_ZERG_FAIL_SOCKET_OP_ERROR         , 290010001)
DEFSYMBOLTOID(ERR_ZERG_GREATER_MAX_LEN_FRAME        , 290010002)
DEFSYMBOLTOID(ERR_ZERG_GREATER_DEFINE_LEN_FRAME     , 290010003)
DEFSYMBOLTOID(ERR_ZERG_SOCKET_CLOSE                 , 290010004)
DEFSYMBOLTOID(ERR_ZERG_SERVER_ALREADY_LONGIN        , 290010006)
DEFSYMBOLTOID(ERR_ZERG_CONNECT_NO_FIND_SVCINFO      , 290010007)
DEFSYMBOLTOID(ERR_ZERG_INIT_RECEIVE_PIPE            , 290010008)
DEFSYMBOLTOID(ERR_ZERG_INIT_SEND_PIPE               , 290010009)
DEFSYMBOLTOID(ERR_ZERG_INIT_ERR_ZERG_PIPE           , 290010010)
DEFSYMBOLTOID(ERR_ZERG_NO_FIND_EVENT_HANDLE         , 290010011)
DEFSYMBOLTOID(ERR_ZERG_RECEIVE_PIPE_IS_FULL         , 290010012)
DEFSYMBOLTOID(ERR_ZERG_SEND_PIPE_IS_FULL            , 290010013)
DEFSYMBOLTOID(ERR_ZERG_ERROR_PIPE_IS_FULL           , 290010014)
DEFSYMBOLTOID(ERR_ZERG_GREAT_THAN_ERROR_TRY         , 290010015)
DEFSYMBOLTOID(ERR_ZERG_MMAP_MALLOC_FAIL             , 290010016)
DEFSYMBOLTOID(ERR_ZERG_INIT_ACCEPT_SOCKET_FAIL      , 290010017)
DEFSYMBOLTOID(ERR_ZERG_GET_STARTUP_CONFIG_FAIL      , 290010018)
DEFSYMBOLTOID(ERR_ZERG_GET_CFGFILE_CONFIG_FAIL      , 290010019)
DEFSYMBOLTOID(ERR_ZERG_GET_AUTO_CONN_CONFIG_FAIL    , 290010020)
DEFSYMBOLTOID(ERR_ZERG_OCCUR_EXCEPTION              , 290010021)
DEFSYMBOLTOID(ERR_ZERG_APPFRAME_ERROR               , 290010022)
DEFSYMBOLTOID(ERR_ZERG_COULD_NOT_ERR_ZERG_PROCESS   , 290010023)
DEFSYMBOLTOID(ERR_ZERG_FORK_FAIL                    , 290010024)
DEFSYMBOLTOID(ERR_ZERG_APPFRAME_CMD_ERROR           , 290010025)
DEFSYMBOLTOID(ERR_ZERG_INIT_TIMER_QUEUE             , 290010026)
DEFSYMBOLTOID(ERR_ZERG_INIT_LISTEN_PORT_FAIL        , 290010027)
DEFSYMBOLTOID(ERR_ZERG_SEND_FRAME_FAIL              , 290010028)
DEFSYMBOLTOID(ERR_ZERG_WRITE_PID_FILE_FAIL          , 290010029)
DEFSYMBOLTOID(ERR_ZERG_UNSAFE_PORT_WARN             , 290010030)
DEFSYMBOLTOID(ERR_ZERG_INIT_UPD_PORT_FAIL           , 290010031)
DEFSYMBOLTOID(ERR_ZERG_IP_RESTRICT_CHECK_FAIL       , 290010032)
DEFSYMBOLTOID(ERR_ZERG_UDPSESSION_NOFOUND           , 290010033)
DEFSYMBOLTOID(ERR_ZERG_UDPSESSION_FULL              , 290010034)
DEFSYMBOLTOID(ERR_ZERG_SVCTYPE_IS_NOT_ALLOW         , 290010035)
DEFSYMBOLTOID(ERR_ZERG_LOAD_OPERATION_KEY_FAIL      , 290010036)
DEFSYMBOLTOID(ERR_ZERG_ISNOT_CONNECT_SERVICES       , 290010037)
DEFSYMBOLTOID(ERR_ZERG_CHOOSE_AUTO_CONNECT_SERVICES , 290010038)
DEFSYMBOLTOID(ERR_ZERG_CONFIG_GET_IP_FROM_CFGSVR    , 290010039)
DEFSYMBOLTOID(ERR_ZERG_END                          , 290019999)

DEFSYMBOLTOID(ERR_OGRE_BEGIN                        , 290020000)
DEFSYMBOLTOID(ERR_OGRE_SOCKET_OP_ERROR              , 290020001)
DEFSYMBOLTOID(ERR_OGRE_SOCKET_CLOSE                 , 290020002)
DEFSYMBOLTOID(ERR_OGRE_RECEIVE_PIPE_IS_FULL         , 290020003)
DEFSYMBOLTOID(ERR_OGRE_ERROR_PIPE_IS_FULL           , 290020004)
DEFSYMBOLTOID(ERR_OGRE_NO_FIND_SERVICES_INFO        , 290020005)
DEFSYMBOLTOID(ERR_OGRE_INIT_LISTEN_PORT_FAIL        , 290020006)
DEFSYMBOLTOID(ERR_OGRE_GREAT_THAN_ERROR_TRY         , 290020007)
DEFSYMBOLTOID(ERR_OGRE_SEND_FRAME_FAIL              , 290020008)
DEFSYMBOLTOID(ERR_OGRE_NO_FIND_EVENT_HANDLE         , 290020009)
DEFSYMBOLTOID(ERR_OGRE_SERVER_ALREADY_LONGIN        , 290020010)
DEFSYMBOLTOID(ERR_OGRE_SEND_FRAME_TOO_LEN           , 290020011)
DEFSYMBOLTOID(ERR_OGRE_INIT_COMM_MANAGER            , 290020012)
DEFSYMBOLTOID(ERR_OGRE_INIT_UDP_PEER                , 290020013)
DEFSYMBOLTOID(ERR_OGRE_UNSAFE_PORT_WARN             , 290020014)
DEFSYMBOLTOID(ERR_OGRE_IP_RESTRICT_CHECK_FAIL       , 290020015)
DEFSYMBOLTOID(ERR_OGRE_GREATER_MAX_LEN_FRAME        , 290020016)
DEFSYMBOLTOID(ERR_OGRE_END                          , 290029999)

ENDDEFSYMBOL

//---------------------------------------------------------------------------------------------

#endif //#ifndef SOARING_LIB_ERROR_CODE_H_

